version: '3'
services:
  database:
    container_name: sql-database
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: todoTask
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      myNetwork:
        aliases:
          - database

networks:
  myNetwork:
