version: '3'
services:
  database:
    container_name: sql-database
    build:
      dockerfile: ./database.Dockerfile
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      myNetwork:
        aliases:
          - database

networks:
  myNetwork:
